# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json
site_url: https://antaanimosity.github.io/build-test/
display_url: https://antaanimosity.github.io/build-test/

logo:
  src: https://antaanimosity.github.io/build-test/favicon.ico
  show_in_header: true

backend:
  name: github
  repo: antaanimosity/build-test # Path to your Gitea repository

media_folder: "assets/img/uploads"
public_folder: "img/uploads"

collections:
  - name: "post" # Used in routes, e.g., /admin/collections/blog
    i18n: true
    label: "Post" # Used in the UI
    folder: "content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", i18n: true, widget: "string" }
      - {
          label: "Publish Date",
          name: "date",
          i18n: duplicate,
          widget: "datetime",
        }
      - { label: "Body", name: "body", i18n: true, widget: "markdown" }
